### ISSUE TITLE
[feature]: Adding a Friends List

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#169]
### Is your feature request related to a problem? Please describe.

Here is my proposed initial code and css for a new FriendsList component.  I was working on the poorly coded Friends component.  I think actually that we should add a panel for:
- a system which recommends a bunch of friends coming from the internal friend matching system, based on user details only.
- We should interally to the app make some distinction between friends and followers, because followers may not be actual friends and friends may not be followers (although that seems redundant.
- Because people will have many friends and followers, this page could get massive. 

Let me know what you think on this and the proposed initial code. @manuel12 @Dylan-Clarry @pawel975 & all.

### Describe the solution you would like

```jsx
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Link, Route, BrowserRouter as Router } from 'react-router-dom';
import { Card, CardContent, CardMedia, Button, TextField, IconButton } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import CloseIcon from '@mui/icons-material/Close';

const FriendsList = () => {
  const [search, setSearch] = useState('');

  useEffect(() => {
    // Perform any necessary operations on component mount, e.g. fetch friends data
  }, []);

  return (
    <Router>
      <div className="FriendsList">
        <div className="FriendsList-header">
          <IconButton>
            <CloseIcon />
          </IconButton>
        </div>
        <div className="FriendsList-content">
          <TextField
            label="Search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            InputProps={{
              endAdornment: (
                <IconButton>
                  <SearchIcon />
                </IconButton>
              ),
            }}
          />
          <div className="FriendsList-cards">
            {Array.from({ length: 10 }, (_, i) => (
              <Card key={i} className="FriendCard">
                <CardMedia
                  component="img"
                  height="200"
                  width="200"
                  image="https://via.placeholder.com/200x200"
                  alt="Friend image"
                />
                <CardContent>
                  <Button variant="contained" color="primary">
                    Add Friend
                  </Button>
                  <Button variant="contained" color="secondary">
                    Remove Friend
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </Router>
  );
};

FriendsList.propTypes = {};

export default FriendsList;
```

```css
.FriendsList {
  width: 1318.8px;
  height: 700px;
  position: absolute;
  left: 50%;
  margin-left: -659.4px;
  overflow: hidden;
}

.FriendsList-header {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  height: 60px;
  background-color: gray;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.FriendsList-content {
  padding: 10px;
}

.FriendsList-cards {
  display: grid;
  grid-template-columns: repeat(5, 200px);
  grid-template-rows: repeat(2, 350px);
  grid-gap: 5px;
  justify-content: center;
}

.FriendCard {
  width: 200px;
  height: 350px;
}
```

### Describe the alternatives you have tried

No matter what I tried the initial code and the solution I worked on seemed very poor.

### Additional context

Not certain of where to go from this code, but I think this code is much better that what is in the Friends component already.
