### ISSUE TITLE
[Bug]: Applying versioning to Dependabot

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#308]
### Describe the Bug

Dependabot could probably use further enhancements to help us.  I think it would currently PR when it finds a patch version update..

I think it would be better if we wait for Major and minor versions and ignore patch versions (according to SemVer 2.0.

Some enhancment could be done with a updates: section in the  .yml

```yml
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    versioning: "widen"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-type: "patch"
      - dependency-type: "indirect"
        update-type: "minor"
```

### Steps to Reproduce

N/A

### Which device are you using?

Linux VM

### Which operating system are you using?

Debian Linux

### Which browser are you using?

Firefox 118

### Contribute

- [X] I am willing to contribute and submit a pull request
