### ISSUE TITLE
[TODO] Complete the Friends compoment

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#78]
**Is your feature request related to a problem?** 
No

Complete the Friends compoment

- Use Material UI for icons, etc
- Friends should ideally be cards that a user could click on to open their profile up in the center panel and display brief information like photo, username, name, location..
I would suggest 6 cards per row in the view.
- The right hand panel/column (200-250px wide in desktop view) could show more controls for friends, etc. in this viewk

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
See above

**Additional context**
I will add some screenshots for inspiration as soon as am able to tomorrow...

**Comment by gbowne1** [comment]
Ideas? @manuel12 @pawel975 @Dylan-Clarry

**Comment by gbowne1** [comment]
Update, I added some initial steps to main tonight as a part of pre-work.  I will have something to actually PR in a few days.

Trying to decide on how to implement a few things like searching for friends as well as a minimal design we can work with.

**Comment by gbowne1** [comment]
Inspiration for a friends list widget

![Screenshot 2023-02-28 at 20-30-59 CodeSandbox](https://user-images.githubusercontent.com/47549872/222045304-20e46050-3815-48f3-a98b-c3d35059a4e8.png)

**Comment by gbowne1** [comment]
Hmm.. the code I used to make more cards in the Suggested Friends panel of the /friends <Friends /> Component doesn't seem to allow it to place cards next to the one I put in as a part of initial work.

**Comment by gbowne1** [comment]
What I have been trrying to accomplish in the past few days in between work sessions.

![ReactSocialTemplate(1)](https://user-images.githubusercontent.com/47549872/224214748-2309c392-6475-41fa-8805-cb50262a79a9.jpg)

**Comment by gbowne1** [comment]
@pawel975 & @manuel12 

Here is some code I propose to add to the friends component to fix the bad code I put in there.

```jsx
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Card, CardContent, CardActions, Button, TextField, IconButton } from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import './FriendsList.css';

const FriendsList = () => {
  const [friends, setFriends] = useState([]);

  useEffect(() => {
    // Load friends from local storage
    const storedFriends = JSON.parse(localStorage.getItem('friends')) || [];
    setFriends(storedFriends);
  }, []);

  // Save friends to local storage
  const saveFriends = updatedFriends => {
    localStorage.setItem('friends', JSON.stringify(updatedFriends));
    setFriends(updatedFriends);
  };

  return (
    <div className="container">
      <div className="header">
        <div sx={{ display: 'flex', alignItems: 'center' }}>
          <TextField label="Search" variant="outlined" size="small" />
          <IconButton color="primary">
            <SearchIcon />
          </IconButton>
        </div>
      </div>
      <div className="cards">
        {friends.map((friend, index) => (
          <Card key={index} sx={{ width: 200, height: 350, marginRight: 5, marginBottom: 5 }}>
            <div sx={{ height: 200, width: 200, backgroundColor: 'lightgray' }}></div>
            <CardContent>{friend.name}</CardContent>
            <CardActions sx={{ justifyContent: 'space-between' }}>
              <Button color="primary" onClick={() => saveFriends(friends.filter((_, i) => i !== index))}>
                Remove Friend
              </Button>
            </CardActions>
          </Card>
        ))}
      </div>
    </div>
  );
};

FriendsList.propTypes = {
  friends: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string.isRequired
    })
  )
};

export default FriendsList;
```

```css
.container {
  width: 1318.8px;
  height: 700px;
  margin: 0 auto;
  padding-left: 250px;
  padding-right: 250px;
  box-sizing: border-box;
  overflow: hidden;
}

.header {
  width: 1318.8px;
  height: 60px;
  background-color: gray;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  padding-right: 20px;
}

.cards {
  display: flex;
  flex-wrap: wrap;
  gap: 5px;
  justify-content: space-between;
}
```
I would like your input before I change this.
